### PR TITLE
Added Support for NestJS 9 and updated README.md

### PR DESCRIPTION
**Pull request by xiifain**

### CODE REVIEW

**Comment by xiifain** [comment]
Added Support For NestJS 9, sentry 7.7.0

**Review by intraordinaire — APPROVED** [review]

**Comment by AlbertHernandez** [comment]
Hi!, there is some news with this pull request?

**Comment by simplenotezy** [comment]
I see that this PR is approved - can we merge it? 😊

**Comment by TheCoordinator** [comment]
Any updates on this?

**Comment by MiniMarker** [comment]
@intraordinaire can you merge this?

**Comment by intraordinaire** [comment]
> @intraordinaire can you merge this?

I don't have the permission :(

**Comment by ntegral** [comment]
We will look to have this and other updates merges by this Friday... Thanks for your support

**Review by ntegral — APPROVED** [review]

**Comment by xiifain** [comment]
Already up to date with current repo's `main` branch and resolved conflicts

**Comment by ntegral** [comment]
Added Support for NestJS 9

**Pull request merged**
